spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wonbae
    driver-class-name: org.postgresql.Driver
    username: wonbae
    password: wonbae
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

  # form에서 update, delete등의 메소드를 사용할 수 있도록 설정한다.
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# log창에 query문이 보인다.
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

